format = """
[](red)\
$os\
$username\
[](bg:blue fg:red)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_status\
[](fg:green bg:cyan)\
$nix_shell\
[](fg:cyan bg:yellow)\
$time\
[ ](fg:yellow)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:red"
style_root = "bg:red"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true      # Disabled by default

[directory]
style = "bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
style = "bg:cyan fg:white"
format = '[via $symbol(\($name\))]($style)'

[elixir]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:green"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = "bg:yellow"
format = '[ $time ]($style)'
